server: src/server.cpp
	g++ -std=c++11 src/server.cpp `pkg-config --libs --cflags opencv` -o server

digraph: src/digraph.cpp
	g++ -std=c++11 src/digraph.cpp -o digraph

sudoku: src/Sudoku.cpp
	g++ -std=c++11 src/Sudoku.cpp -o Sudoku
